name: job1
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        run: |
            docker build . -t ${{ secrets.ACR_ENDPOINT }}/hello2world:${{ github.sha }}
            docker push ${{ secrets.ACR_ENDPOINT }}/hello2world${{ github.sha }}
